name = "EGMInterpolation"
uuid = "d2216c3f-a8b3-467e-80da-a34a198f786c"
authors = ["Zoltán Rácz"]
version = "0.1.0"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
